
[package]
name = "surf"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = { version = "1.0.1", default-features = false }
fyrox = {workspace = true}

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]
