
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
surf = { path = "../game", default-features = false }

[features]
default = ["surf/default"]
dylib-engine = ["surf/dylib-engine"]
